/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_xujianhua_myapplication_MediaPlayer */

#ifndef _Included_com_example_xujianhua_myapplication_MediaPlayer
#define _Included_com_example_xujianhua_myapplication_MediaPlayer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_xujianhua_myapplication_MediaPlayer
 * Method:    print
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_example_xujianhua_myapplication_MediaPlayer_print
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_example_xujianhua_myapplication_MediaPlayer
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_xujianhua_myapplication_MediaPlayer_getName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
